SELECT COUNT(METHOD_ID, TITLE, STAGE, BOB, SINGLE , NOTATION) FROM METHOD Where BOB = ''

SELECT * FROM PERFORMANCE JOIN RINGER ON PERFORMANCE.PERFORMANCE_ID = RINGER.PERFORMANCE_ID

SELECT PERFORMANCE.METHOD, PERFORMANCE.CHANGES, PERFORMANCE.DATE, PERFORMANCE.TENOR, RINGER.NAME, RINGER.BELL, TOWER.DEDICATION, TOWER.DIOCESE FROM PERFORMANCE JOIN RINGER ON PERFORMANCE.PERFORMANCE_ID = RINGER.PERFORMANCE_ID JOIN TOWER ON PERFORMANCE.TOWER_BASE_ID = TOWER.TOWER_BASE_ID